version: 0.0
os: linux
files:
  - source: /
    destination: /absolute path to your app
    overwrite: yes
    exclude:
      - app/**
permissions:
  - object: /absolute path to your app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
