version: 0.0
os: linux
files:
  - source: /
    destination: /testRepo/app
    overwrite: yes
    exclude:
      - app/**
      - db_data/**
      - certs/**
permissions:
  - object: /testRepo/app
    pattern: "**"
    owner: root
    group: root
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
